### ISSUE TITLE
Unable to preview non-saved files.

### ISSUE THREAD

**Issue by mikebronner** [lloeki/svg-preview#3] opened 2014-05-16 17:59 UTC
If I open a new editor window and try to preview the SVG, it won't work. Perhaps the preview could take the editor content and save a temp. file for preview purposes?

**Comment by lloeki** [comment] 2015-02-16 20:26
Please see if this issue can be reproduced with 0.5.0

**Comment by mikebronner** [comment] 2015-02-17 16:31
Unfortunately I'm no longer using Atom for the time being, but maybe someone else using Atom could jump in and help me out? :) Thanks for looking into this!

**Comment by lloeki** [comment] 2015-02-17 16:34
Ok, since I can preview new, unsaved files properly, I assume this has been fixed by the recent update.

**Closed by lloeki** 2015-02-17 16:34 UTC
